events { worker_connections 1024; }

http {
    upstream backend_api {
        server api-01:80;
        server api-02:80;
    }

    server {
        listen 80;
        server_name api.local;

        # Ocultar versão para segurança
        server_tokens off;

        location / {
            proxy_pass http://backend_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}