# Definição dos servidores de Banco de Dados (PostgreSQL)
[db_servers]
db-primary   ansible_connection=docker
db-standby   ansible_connection=docker

# Definição dos servidores de Mensageria (Kafka Cluster)
[kafka_nodes]
kafka-01     ansible_connection=docker
kafka-02     ansible_connection=docker
kafka-03     ansible_connection=docker

# Definição dos servidores de Cache (Redis)
[cache_nodes]
redis-master ansible_connection=docker
redis-slave  ansible_connection=docker

# Definição da Camada de Entrada (Nginx)
[gateway]
nginx-lb     ansible_connection=docker

# Variáveis globais para todos os grupos (ex: Python interpreter)
[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_remote_tmp=/tmp